# Generated by Django 5.1.5 on 2025-01-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('summ', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.category')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.type')),
            ],
        ),
        migrations.CreateModel(
            name='Undercat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.category')),
            ],
        ),
        migrations.CreateModel(
            name='Undercat_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashflow_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.cashflow')),
                ('undercat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.undercat')),
            ],
        ),
    ]
