# Generated by Django 5.1.5 on 2025-01-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Undercat_list',
            new_name='UndercatList',
        ),
    ]
