# Generated by Django 5.1.5 on 2025-01-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_rename_undercat_list_undercatlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.category'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.status'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.type'),
        ),
        migrations.AlterField(
            model_name='undercat',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.category'),
        ),
        migrations.AlterField(
            model_name='undercatlist',
            name='cashflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.cashflow'),
        ),
        migrations.AlterField(
            model_name='undercatlist',
            name='undercat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.undercat'),
        ),
    ]
