# Generated by Django 5.1.5 on 2025-01-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_cashflow_category_id_alter_cashflow_status_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='undercat',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cashflow.category'),
        ),
    ]
