# Generated by Django 5.1.5 on 2025-01-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_remove_cashflow_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflow.category'),
            preserve_default=False,
        ),
    ]
